AWSTemplateFormatVersion: '2010-09-09'
Description: PR Review System - Converted from AWS SAM to raw CloudFormation

Resources:

  # SNS Topics
  PrRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: pr-request-automation-topic

  PrReviewTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: pr-review-automation-topic

  # IAM Roles
  PrRequestFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowPublishToPrRequestTopic
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sns:Publish
                Resource: "*"

  PrReviewFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowPublishToPrReviewTopic
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sns:Publish
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: "*"

  # Lambda Functions
  HealthCheckFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: health-check-function
      Code:
        S3Bucket: your-bucket-name
        S3Key: health_check.zip
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::your-account-id:role/service-role/lambda-basic-role
      Timeout: 3

  PrRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: pr-request-function
      Code:
        S3Bucket: your-bucket-name
        S3Key: pr_request.zip
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: !GetAtt PrRequestFunctionRole.Arn
      Timeout: 3
      Environment:
        Variables:
          PR_REQUEST_TOPIC_ARN: !Ref PrRequestTopic

  PrReviewFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: pr-review-function
      Code:
        S3Bucket: your-bucket-name
        S3Key: pr_review.zip
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 40
      Role: !GetAtt PrReviewFunctionRole.Arn
      Environment:
        Variables:
          PR_REVIEW_TOPIC_ARN: !Ref PrReviewTopic
          GIT_API_KEY: ""
          ANTHROPIC_API_KEY: ""

  # API Gateway Rest API
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PRReviewAPI

  ApiGatewayRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      PathPart: prrequest
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayHealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      PathPart: health
      RestApiId: !Ref ApiGatewayRestApi

  # API Gateway Methods
  PrRequestMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ApiGatewayRootResource
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PrRequestFunction.Arn}/invocations

  HealthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ApiGatewayHealthResource
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations

  # API Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PrRequestMethod
      - HealthMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: Prod

  # SNS Event Source Mapping (manual for PrReviewFunction)
  PrRequestTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref PrRequestTopic
      Protocol: lambda
      Endpoint: !GetAtt PrReviewFunction.Arn

  PrReviewInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PrReviewFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref PrRequestTopic

Outputs:
  HealthApiUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health"

  PrRequestApiUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/prrequest"

  PrRequestTopicArn:
    Value: !Ref PrRequestTopic

  PrReviewTopicArn:
    Value: !Ref PrReviewTopic