AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple SAM Lambda app with two endpoints

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get
        PrRequestApi:
          Type: Api
          Properties:
            Path: /prrequest
            Method: post

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
